In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MultiLabelBinarizer

In [2]:
df_list = ['dfmajorcrimes', 'dfhomicidies']

In [3]:
dfmajorcrimes = pd.read_csv('raw_data/majorcrimes.csv')
dfhomicides = pd.read_csv('raw_data/homicidies.csv')

In [4]:
def show_all_columns(df):
    with pd.option_context('display.max_columns', None):
        display(df)
def show_all_rows(df):
    with pd.option_context('display.max_rows', None):
        display(df)

In [5]:
import pandas as pd

# Assuming the DataFrames dfhomicides, dfbicycle, dfmajorcrimes, dfshooting_firearm are already defined

# Define the target columns including the ones that need to be added
columns = ['EVENT_UNIQUE_ID','DATASET','OFFENCE', 'MCI_CATEGORY','OCC_HOUR','OCC_DAY','OCC_MONTH','OCC_YEAR','OCC_DOW','OCC_DOY','LAT_WGS84','LONG_WGS84']

# Add missing columns with default values
for df in [dfhomicides, dfmajorcrimes]:
    for column in columns:
        if column not in df.columns:
            df[column] = None

# Select columns in the specified order for all DataFrames
dfhomicides_s = dfhomicides[columns]
dfmajorcrimes_s = dfmajorcrimes[columns]

# Set the 'DATASET' column for each DataFrame using .loc to avoid SettingWithCopyWarning
dfhomicides_s.loc[:, 'DATASET'] = 'HOMICIDES'
dfmajorcrimes_s.loc[:, 'DATASET'] = 'MAJOR_CRIMES'

# Concatenate the DataFrames into a single DataFrame
dfmatrix = pd.concat([dfhomicides_s, dfmajorcrimes_s], ignore_index=True)

# Display the resulting DataFrame
dfmatrix

,EVENT_UNIQUE_ID,DATASET,OFFENCE,MCI_CATEGORY,OCC_HOUR,OCC_DAY,OCC_MONTH,OCC_YEAR,OCC_DOW,OCC_DOY,LAT_WGS84,LONG_WGS84
0,GO-2004111878,HOMICIDES,None,None,None,3.0,January,2004.0,Saturday,3.0,43.685026,-79.392828
1,GO-2004125755,HOMICIDES,None,None,None,8.0,January,2004.0,Thursday,8.0,43.781782,-79.233852
2,GO-2004136086,HOMICIDES,None,None,None,8.0,January,2004.0,Thursday,8.0,43.810544,-79.205574
3,GO-2004148623,HOMICIDES,None,None,None,25.0,January,2004.0,Sunday,25.0,43.670467,-79.434387
4,GO-2004148619,HOMICIDES,None,None,None,25.0,January,2004.0,Sunday,25.0,43.822997,-79.204958
...,...,...,...,...,...,...,...,...,...,...,...,...
386096,GO-2024688981,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,16,30.0,March,2024.0,Saturday,90.0,43.755641,-79.196001
386097,GO-2024690900,MAJOR_CRIMES,Assault,Assault,16,31.0,March,2024.0,Sunday,91.0,43.595354,-79.529766
386098,GO-2024690985,MAJOR_CRIMES,Assault,Assault,16,31.0,March,2024.0,Sunday,91.0,43.688644,-79.391479
386099,GO-2024690995,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,23,30.0,March,2024.0,Saturday,90.0,43.684335,-79.372581
386100,GO-2024688279,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,19,30.0,March,2024.0,Saturday,90.0,43.781143,-79.152912

In [6]:
print("\nNumber of duplicate rows:", dfmatrix.duplicated().sum())

Number of duplicate rows: 28185

In [7]:
dfmatrix['EVENT_UNIQUE_ID'].value_counts()

EVENT_UNIQUE_ID
GO-20151785704    24
GO-201967831      23
GO-2023651649     21
GO-20231711203    21
GO-20222426282    20
                  ..
GO-2018110281      1
GO-2018106819      1
GO-2018106826      1
GO-2018106899      1
GO-2024688279      1
Name: count, Length: 336610, dtype: int64

In [8]:
dfmatrix.loc[dfmatrix['DATASET'] == 'HOMICIDES', 'OFFENCE'] = 'Homicide'
dfmatrix.loc[dfmatrix['DATASET'] == 'HOMICIDES', 'MCI_CATEGORY'] = 'Homicide'
dfmatrix

,EVENT_UNIQUE_ID,DATASET,OFFENCE,MCI_CATEGORY,OCC_HOUR,OCC_DAY,OCC_MONTH,OCC_YEAR,OCC_DOW,OCC_DOY,LAT_WGS84,LONG_WGS84
0,GO-2004111878,HOMICIDES,Homicide,Homicide,None,3.0,January,2004.0,Saturday,3.0,43.685026,-79.392828
1,GO-2004125755,HOMICIDES,Homicide,Homicide,None,8.0,January,2004.0,Thursday,8.0,43.781782,-79.233852
2,GO-2004136086,HOMICIDES,Homicide,Homicide,None,8.0,January,2004.0,Thursday,8.0,43.810544,-79.205574
3,GO-2004148623,HOMICIDES,Homicide,Homicide,None,25.0,January,2004.0,Sunday,25.0,43.670467,-79.434387
4,GO-2004148619,HOMICIDES,Homicide,Homicide,None,25.0,January,2004.0,Sunday,25.0,43.822997,-79.204958
...,...,...,...,...,...,...,...,...,...,...,...,...
386096,GO-2024688981,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,16,30.0,March,2024.0,Saturday,90.0,43.755641,-79.196001
386097,GO-2024690900,MAJOR_CRIMES,Assault,Assault,16,31.0,March,2024.0,Sunday,91.0,43.595354,-79.529766
386098,GO-2024690985,MAJOR_CRIMES,Assault,Assault,16,31.0,March,2024.0,Sunday,91.0,43.688644,-79.391479
386099,GO-2024690995,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,23,30.0,March,2024.0,Saturday,90.0,43.684335,-79.372581
386100,GO-2024688279,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,19,30.0,March,2024.0,Saturday,90.0,43.781143,-79.152912

In [9]:
# checking for latitude and longitude errors

# Toronto boundaries
north_boundary = 43.8554
south_boundary = 43.5810
east_boundary = -79.1161
west_boundary = -79.6393

# Check if latitude and longitude are within the boundaries
within_boundaries = (dfmatrix['LAT_WGS84'] <= north_boundary) & (dfmatrix['LAT_WGS84'] >= south_boundary) & \
                    (dfmatrix['LONG_WGS84'] >= west_boundary) & (dfmatrix['LONG_WGS84'] <= east_boundary)

# Filter the DataFrame
data_within_toronto = dfmatrix[within_boundaries]

data_within_toronto

,EVENT_UNIQUE_ID,DATASET,OFFENCE,MCI_CATEGORY,OCC_HOUR,OCC_DAY,OCC_MONTH,OCC_YEAR,OCC_DOW,OCC_DOY,LAT_WGS84,LONG_WGS84
0,GO-2004111878,HOMICIDES,Homicide,Homicide,None,3.0,January,2004.0,Saturday,3.0,43.685026,-79.392828
1,GO-2004125755,HOMICIDES,Homicide,Homicide,None,8.0,January,2004.0,Thursday,8.0,43.781782,-79.233852
2,GO-2004136086,HOMICIDES,Homicide,Homicide,None,8.0,January,2004.0,Thursday,8.0,43.810544,-79.205574
3,GO-2004148623,HOMICIDES,Homicide,Homicide,None,25.0,January,2004.0,Sunday,25.0,43.670467,-79.434387
4,GO-2004148619,HOMICIDES,Homicide,Homicide,None,25.0,January,2004.0,Sunday,25.0,43.822997,-79.204958
...,...,...,...,...,...,...,...,...,...,...,...,...
386096,GO-2024688981,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,16,30.0,March,2024.0,Saturday,90.0,43.755641,-79.196001
386097,GO-2024690900,MAJOR_CRIMES,Assault,Assault,16,31.0,March,2024.0,Sunday,91.0,43.595354,-79.529766
386098,GO-2024690985,MAJOR_CRIMES,Assault,Assault,16,31.0,March,2024.0,Sunday,91.0,43.688644,-79.391479
386099,GO-2024690995,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,23,30.0,March,2024.0,Saturday,90.0,43.684335,-79.372581
386100,GO-2024688279,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,19,30.0,March,2024.0,Saturday,90.0,43.781143,-79.152912

In [10]:
data_within_toronto2 = dfmatrix[
     (dfmatrix['LONG_WGS84'] < -78.0000)]

data_within_toronto2

,EVENT_UNIQUE_ID,DATASET,OFFENCE,MCI_CATEGORY,OCC_HOUR,OCC_DAY,OCC_MONTH,OCC_YEAR,OCC_DOW,OCC_DOY,LAT_WGS84,LONG_WGS84
0,GO-2004111878,HOMICIDES,Homicide,Homicide,None,3.0,January,2004.0,Saturday,3.0,43.685026,-79.392828
1,GO-2004125755,HOMICIDES,Homicide,Homicide,None,8.0,January,2004.0,Thursday,8.0,43.781782,-79.233852
2,GO-2004136086,HOMICIDES,Homicide,Homicide,None,8.0,January,2004.0,Thursday,8.0,43.810544,-79.205574
3,GO-2004148623,HOMICIDES,Homicide,Homicide,None,25.0,January,2004.0,Sunday,25.0,43.670467,-79.434387
4,GO-2004148619,HOMICIDES,Homicide,Homicide,None,25.0,January,2004.0,Sunday,25.0,43.822997,-79.204958
...,...,...,...,...,...,...,...,...,...,...,...,...
386096,GO-2024688981,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,16,30.0,March,2024.0,Saturday,90.0,43.755641,-79.196001
386097,GO-2024690900,MAJOR_CRIMES,Assault,Assault,16,31.0,March,2024.0,Sunday,91.0,43.595354,-79.529766
386098,GO-2024690985,MAJOR_CRIMES,Assault,Assault,16,31.0,March,2024.0,Sunday,91.0,43.688644,-79.391479
386099,GO-2024690995,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,23,30.0,March,2024.0,Saturday,90.0,43.684335,-79.372581
386100,GO-2024688279,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,19,30.0,March,2024.0,Saturday,90.0,43.781143,-79.152912

In [11]:
dfmatrix = dfmatrix.loc[within_boundaries].reset_index(drop=True)
dfmatrix

,EVENT_UNIQUE_ID,DATASET,OFFENCE,MCI_CATEGORY,OCC_HOUR,OCC_DAY,OCC_MONTH,OCC_YEAR,OCC_DOW,OCC_DOY,LAT_WGS84,LONG_WGS84
0,GO-2004111878,HOMICIDES,Homicide,Homicide,None,3.0,January,2004.0,Saturday,3.0,43.685026,-79.392828
1,GO-2004125755,HOMICIDES,Homicide,Homicide,None,8.0,January,2004.0,Thursday,8.0,43.781782,-79.233852
2,GO-2004136086,HOMICIDES,Homicide,Homicide,None,8.0,January,2004.0,Thursday,8.0,43.810544,-79.205574
3,GO-2004148623,HOMICIDES,Homicide,Homicide,None,25.0,January,2004.0,Sunday,25.0,43.670467,-79.434387
4,GO-2004148619,HOMICIDES,Homicide,Homicide,None,25.0,January,2004.0,Sunday,25.0,43.822997,-79.204958
...,...,...,...,...,...,...,...,...,...,...,...,...
380240,GO-2024688981,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,16,30.0,March,2024.0,Saturday,90.0,43.755641,-79.196001
380241,GO-2024690900,MAJOR_CRIMES,Assault,Assault,16,31.0,March,2024.0,Sunday,91.0,43.595354,-79.529766
380242,GO-2024690985,MAJOR_CRIMES,Assault,Assault,16,31.0,March,2024.0,Sunday,91.0,43.688644,-79.391479
380243,GO-2024690995,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,23,30.0,March,2024.0,Saturday,90.0,43.684335,-79.372581
380244,GO-2024688279,MAJOR_CRIMES,Theft Of Motor Vehicle,Auto Theft,19,30.0,March,2024.0,Saturday,90.0,43.781143,-79.152912

In [12]:
dfmatrix['MCI_CATEGORY'].value_counts()

MCI_CATEGORY
Assault            200274
Break and Enter     71633
Auto Theft          60526
Robbery             33738
Theft Over          12660
Homicide             1414
Name: count, dtype: int64

In [13]:
dfmatrix['OFFENCE'].value_counts()

OFFENCE
Assault                           136962
Theft Of Motor Vehicle             60526
B&E                                60237
Assault With Weapon                34264
B&E W'Intent                        8977
Robbery - Mugging                   8950
Assault Bodily Harm                 8666
Theft Over                          7066
Assault Peace Officer               6371
Robbery With Weapon                 6183
Robbery - Other                     5641
Robbery - Business                  5080
Assault - Resist/ Prevent Seiz      3420
Theft From Motor Vehicle Over       3111
Aggravated Assault                  2884
Robbery - Swarming                  2511
Discharge Firearm With Intent       2314
Unlawfully In Dwelling-House        2274
Discharge Firearm - Recklessly      1677
Theft From Mail / Bag / Key         1481
Homicide                            1414
Robbery - Home Invasion             1358
Pointing A Firearm                  1353
Robbery - Vehicle Jacking           1283
Robbery - Purse Snatch              1107
Robbery - Financial Institute        894
Assault Peace Officer Wpn/Cbh        751
Theft Over - Shoplifting             627
Administering Noxious Thing          614
Assault - Force/Thrt/Impede          428
Robbery - Delivery Person            303
Robbery - Taxi                       262
Use Firearm / Immit Commit Off       210
Theft Over - Bicycle                 180
Theft Over - Distraction             149
Disarming Peace/Public Officer       132
Crim Negligence Bodily Harm          130
Robbery - Atm                        118
B&E Out                              116
Robbery - Armoured Car                46
Theft - Misapprop Funds Over          38
Air Gun Or Pistol: Bodily Harm        31
Aggravated Aslt Peace Officer         28
Aggravated Assault Avails Pros        19
B&E - To Steal Firearm                16
Unlawfully Causing Bodily Harm        15
B&E - M/Veh To Steal Firearm          13
Theft Of Utilities Over                8
Traps Likely Cause Bodily Harm         2
Set/Place Trap/Intend Death/Bh         2
Robbery To Steal Firearm               2
Hoax Terrorism Causing Bodily          1
Name: count, dtype: int64

In [19]:
import math

for i, hour_row in df_hour.iterrows():
    size = len(dfmatrix[dfmatrix['DATASET']=='HOMICIDES'])
    for index, row in dfmatrix[((dfmatrix['DATASET']=='HOMICIDES') & (pd.isnull(dfmatrix.OCC_HOUR)))].head(math.trunc(size*hour_row['count'])).iterrows():
        dfmatrix.loc[index, 'OCC_HOUR'] = hour_row['OCC_HOUR']

In [21]:
# # Display NA values

# # Boolean mask where OCC_HOUR is NA
# na_mask = dfmatrix['OCC_HOUR'].isna()

# # Mask to filter the DataFrame
# na_rows = dfmatrix[na_mask]

# # Display the rows with NA values in OCC_HOUR column
# na_rows

,EVENT_UNIQUE_ID,DATASET,OFFENCE,MCI_CATEGORY,OCC_HOUR,OCC_DAY,OCC_MONTH,OCC_YEAR,OCC_DOW,OCC_DOY,LAT_WGS84,LONG_WGS84
1400,GO-2024166708,HOMICIDES,Homicide,Homicide,None,23.0,January,2024.0,Tuesday,23.0,43.679072,-79.339804
1401,GO-2024275367,HOMICIDES,Homicide,Homicide,None,6.0,February,2024.0,Tuesday,37.0,43.653848,-79.441131
1402,GO-2024308909,HOMICIDES,Homicide,Homicide,None,10.0,February,2024.0,Saturday,41.0,43.700155,-79.516192
1403,GO-2024363811,HOMICIDES,Homicide,Homicide,None,17.0,February,2024.0,Saturday,48.0,43.765900,-79.519675
1404,GO-2024434274,HOMICIDES,Homicide,Homicide,None,27.0,February,2024.0,Tuesday,58.0,43.699278,-79.519837
1405,GO-2024434274,HOMICIDES,Homicide,Homicide,None,27.0,February,2024.0,Tuesday,58.0,43.699278,-79.519837
1406,GO-2024453371,HOMICIDES,Homicide,Homicide,None,29.0,February,2024.0,Thursday,60.0,43.734669,-79.600963
1407,GO-2024480054,HOMICIDES,Homicide,Homicide,None,3.0,March,2024.0,Sunday,63.0,43.713413,-79.559752
1408,GO-2024511473,HOMICIDES,Homicide,Homicide,None,7.0,March,2024.0,Thursday,67.0,43.641113,-79.561860
1409,GO-2024545700,HOMICIDES,Homicide,Homicide,None,12.0,March,2024.0,Tuesday,72.0,43.659103,-79.364238
1410,GO-2024545700,HOMICIDES,Homicide,Homicide,None,12.0,March,2024.0,Tuesday,72.0,43.659103,-79.364238
1411,GO-2024558575,HOMICIDES,Homicide,Homicide,None,14.0,March,2024.0,Thursday,74.0,43.745156,-79.208993
1412,GO-2024671809,HOMICIDES,Homicide,Homicide,None,28.0,March,2024.0,Thursday,88.0,43.768847,-79.466916
1413,GO-2024673427,HOMICIDES,Homicide,Homicide,None,29.0,March,2024.0,Friday,89.0,43.733742,-79.538218

In [22]:
# # Filter the DataFrame for rows where DATASET is HOMICIDES
# homicides_df = dfmatrix[dfmatrix['DATASET'] == 'HOMICIDES']

# # Perform value_counts() on the OCC_HOUR column
# occ_hour_counts = homicides_df['OCC_HOUR'].value_counts()

# occ_hour_counts

OCC_HOUR
0.0     97
21.0    77
12.0    76
20.0    76
18.0    76
22.0    76
23.0    73
19.0    73
17.0    70
15.0    68
16.0    65
2.0     57
1.0     57
14.0    57
13.0    53
11.0    49
3.0     47
10.0    47
9.0     46
8.0     39
4.0     38
5.0     29
7.0     29
6.0     25
Name: count, dtype: int64

In [23]:
# # Again for the 14 remainders still showing as Nan

# for i, hour_row in df_hour.iterrows():
#     size = len(dfmatrix[dfmatrix['DATASET']=='HOMICIDES'])
#     for index, row in dfmatrix[((dfmatrix['DATASET']=='HOMICIDES') & (pd.isnull(dfmatrix.OCC_HOUR)))].head(math.trunc(size*hour_row['count'])).iterrows():
#         dfmatrix.loc[index, 'OCC_HOUR'] = hour_row['OCC_HOUR']

In [24]:
len(dfmatrix[pd.isnull(dfmatrix['OCC_HOUR'])])

0

In [ ]:
# months = {'January':1,
#           'February': 2,
#           'March': 3,
#           'April':4,
#           'May': 5,
#           'June': 6,
#           'July': 7,
#           'August': 8,
#           'September': 9,
#           'October': 10,
#           'November': 11,
#           'December': 12}

In [ ]:
# dfmatrix['OCC_HOUR'] = pd.to_numeric(dfmatrix['OCC_HOUR'], errors='raise').fillna(0).astype(int)
# dfmatrix['OCC_DAY'] = pd.to_numeric(dfmatrix['OCC_DAY'], errors='raise').fillna(0).astype(int)
# dfmatrix.loc['OCC_YEAR'] = pd.to_numeric(dfmatrix['OCC_YEAR'], errors='raise').fillna(0).astype(int)

In [ ]:
# import math
# df_hour = dfmatrix[dfmatrix['DATASET']== 'MAJOR_CRIMES'].OCC_HOUR.value_counts()/len(dfmatrix[dfmatrix['DATASET']== 'MAJOR_CRIMES'])
# df_hour = df_hour.to_frame().reset_index(drop=False)

# for i, hour_row in df_hour.iterrows():
#     size = len(dfmatrix[dfmatrix['DATASET']=='HOMICIDES'])
#     for index, row in dfmatrix[((dfmatrix['DATASET']=='HOMICIDES') & (pd.isnull(dfmatrix.OCC_HOUR)))].head(math.trunc(size*hour_row['count'])).iterrows():
#         dfmatrix.loc[index, 'OCC_HOUR'] = hour_row['OCC_HOUR']

In [ ]:
# dfmatrix = dfmatrix[(dfmatrix.OCC_YEAR > 0)]

In [ ]:
# dfmatrix['OCC_MONTH_NUM'] = dfmatrix.OCC_MONTH.apply(lambda x: months[x])

In [ ]:
dfmatrix.info()

In [ ]:
# # Apply sine and cosine transformations
# dfmatrix['MONTH_SIN'] = np.sin(2 * np.pi * dfmatrix['OCC_MONTH_NUM'] / 12)
# dfmatrix['MONTH_COS'] = np.cos(2 * np.pi * dfmatrix['OCC_MONTH_NUM'] / 12)
# dfmatrix['HOUR_SIN'] = np.sin(2 * np.pi * dfmatrix['OCC_HOUR'] / 24)
# dfmatrix['HOUR_COS'] = np.cos(2 * np.pi * dfmatrix['OCC_HOUR'] / 24)

In [ ]:
dfmatrix

In [ ]:
dfmatrix = dfmatrix.drop(columns=['DATASET', 'OFFENCE'])
dfmatrix

In [ ]:
# # Agrupar por 'LAT_WGS84' e 'LONG_WGS84' e contar valores distintos de 'OCC_HOUR'
# distinct_hours = dfmatrix.groupby(['LAT_WGS84', 'LONG_WGS84'])['OCC_HOUR'].nunique().reset_index()

# # Filtrar para encontrar coordenadas com mÃºltiplos valores distintos
# multiple_distinct_hours = distinct_hours[distinct_hours['OCC_HOUR'] > 1]

# multiple_distinct_hours.value_counts()

In [ ]:
# # Agrupar por 'LAT_WGS84' e 'LONG_WGS84' e contar valores distintos de 'OCC_DAY'
# distinct_hours = dfmatrix.groupby(['LAT_WGS84', 'LONG_WGS84'])['OCC_DAY'].nunique().reset_index()

# # Filtrar para encontrar coordenadas com mÃºltiplos valores distintos
# multiple_distinct_hours = distinct_hours[distinct_hours['OCC_DAY'] > 1]

# multiple_distinct_hours.value_counts()

In [ ]:

# # Agrupar por 'EVENT_UNIQUE_ID', 'LAT_WGS84' e 'LONG_WGS84' e contar as ocorrÃªncias de cada categoria
# df_grouped = dfmatrix.groupby(['EVENT_UNIQUE_ID', 'LAT_WGS84', 'LONG_WGS84']).agg({
#     'MCI_CATEGORY': lambda x: list(x),
#     'OCC_YEAR': 'first',
#     'OCC_MONTH': 'first',
#     'OCC_DAY': 'first',
#     'OCC_HOUR': 'first'
# }).reset_index()

In [ ]:
# dfmatrix['MCI_CATEGORY'] = dfmatrix['MCI_CATEGORY'].apply(lambda x: [x])
# df_grouped2 = dfmatrix.groupby(['EVENT_UNIQUE_ID', 'LAT_WGS84', 'LONG_WGS84']).agg({
#     'MCI_CATEGORY': lambda x: sum(x, []),
#     'OCC_YEAR': 'first',
#     'OCC_MONTH': 'first',
#     'OCC_DAY': 'first',
#     'OCC_HOUR': 'first'
# }).reset_index()

In [ ]:
# df_grouped2['MCI_CATEGORY'].value_counts()

In [ ]:
# Agrupar por 'EVENT_UNIQUE_ID', 'LAT_WGS84' e 'LONG_WGS84' e contar as ocorrÃªncias de cada categoria
dfmatrix['MCI_CATEGORY'] = dfmatrix['MCI_CATEGORY'].apply(lambda x: [x])
df_grouped = dfmatrix.groupby(['EVENT_UNIQUE_ID', 'LAT_WGS84', 'LONG_WGS84']).agg({
    'MCI_CATEGORY': lambda x: sum(x, []),
    'OCC_YEAR': 'first',
    'OCC_MONTH': 'first',
    'OCC_DAY': 'first',
    'OCC_HOUR': 'first'
}).reset_index()

In [ ]:
# Binarizar as categorias de crimes usando MultiLabelBinarizer
mlb = MultiLabelBinarizer()
crime_counts = pd.DataFrame(mlb.fit_transform(df_grouped['MCI_CATEGORY']), columns=mlb.classes_)
crime_counts

In [ ]:
crime_counts['Homicide'].value_counts()

In [ ]:
# Ajustar a contagem de crimes
for column in crime_counts.columns:
    crime_counts[column] = df_grouped['MCI_CATEGORY'].apply(lambda x: x.count(column))

In [ ]:
## Concatenar as contagens de crimes com o DataFrame original
#df_final = pd.concat([df_grouped.drop(columns=['MCI_CATEGORY']), crime_counts], axis=1).fillna(0)

##/tmp/ipykernel_22894/797639399.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

In [ ]:
# Concatenar as contagens de crimes com o DataFrame original
df_final = pd.concat([df_grouped.drop(columns=['MCI_CATEGORY']), crime_counts], axis=1)

# Inferir tipos de objeto e preencher valores nulos
df_final = df_final.infer_objects().fillna(0)

In [ ]:
df_final.head()

In [ ]:
df_final['Homicide'].value_counts()

In [ ]:
df_final['Assault'].value_counts()

In [ ]:
print("\nNumber of duplicate rows:", df_final.duplicated().sum())

In [ ]:
df_final.shape

In [ ]:
# Selecionar as colunas de features e de rÃ³tulos
feature_columns = ['OCC_YEAR', 'OCC_MONTH', 'OCC_DAY', 'OCC_HOUR', 'LAT_WGS84', 'LONG_WGS84']
label_columns = list(crime_counts.columns)

# Separar features e rÃ³tulos
X = df_final[feature_columns].values
y = df_final[label_columns].values

# Normalizar as features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)