In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Load the dataset from the provided WSL path
file_path = 'raw_data/Major_Crime_Indicators_Open_Data.csv'

crime_data = pd.read_csv(file_path)

# Display the first few rows of the dataset
crime_data

,X,Y,OBJECTID,EVENT_UNIQUE_ID,REPORT_DATE,OCC_DATE,REPORT_YEAR,REPORT_MONTH,REPORT_DAY,REPORT_DOY,...,UCR_CODE,UCR_EXT,OFFENCE,MCI_CATEGORY,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84
0,-8.841785e+06,5.410286e+06,1,GO-20141260127,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,...,1420,110,Assault Bodily Harm,Assault,84,Little Portugal,84,Little Portugal (84),-79.427105,43.642517
1,-8.838126e+06,5.412178e+06,2,GO-20141263725,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,...,1420,100,Assault With Weapon,Assault,78,Kensington-Chinatown,78,Kensington-Chinatown (78),-79.394234,43.654811
2,-8.841053e+06,5.409639e+06,3,GO-20141264272,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,...,1420,100,Assault With Weapon,Assault,85,South Parkdale,85,South Parkdale (85),-79.420532,43.638306
3,-8.850461e+06,5.420267e+06,4,GO-20141263706,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,...,1430,100,Assault,Assault,113,Weston,113,Weston (113),-79.505043,43.707365
4,-8.840470e+06,5.431266e+06,5,GO-20141263710,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,...,1430,100,Assault,Assault,151,Yonge-Doris,51,Willowdale East (51),-79.415293,43.778743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384682,-8.816058e+06,5.427705e+06,384683,GO-2024688981,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,...,2135,210,Theft Of Motor Vehicle,Auto Theft,136,West Hill,136,West Hill (136),-79.196001,43.755641
384683,-8.853213e+06,5.403034e+06,384684,GO-2024690900,2024/03/31 04:00:00+00,2024/03/31 04:00:00+00,2024,March,31,91,...,1430,100,Assault,Assault,19,Long Branch,19,Long Branch (19),-79.529766,43.595354
384684,-8.837819e+06,5.417385e+06,384685,GO-2024690985,2024/03/31 04:00:00+00,2024/03/31 04:00:00+00,2024,March,31,91,...,1430,100,Assault,Assault,98,Rosedale-Moore Park,98,Rosedale-Moore Park (98),-79.391479,43.688644
384685,-8.835715e+06,5.416722e+06,384686,GO-2024690995,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,...,2135,210,Theft Of Motor Vehicle,Auto Theft,98,Rosedale-Moore Park,98,Rosedale-Moore Park (98),-79.372581,43.684335
384686,-8.811262e+06,5.431636e+06,384687,GO-2024688279,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,...,2135,210,Theft Of Motor Vehicle,Auto Theft,133,Centennial Scarborough,133,Centennial Scarborough (133),-79.152912,43.781143

In [3]:
# Identify duplicate rows
duplicates = crime_data[crime_data.duplicated()]

# Display duplicate rows
print(duplicates)

Empty DataFrame
Columns: [X, Y, OBJECTID, EVENT_UNIQUE_ID, REPORT_DATE, OCC_DATE, REPORT_YEAR, REPORT_MONTH, REPORT_DAY, REPORT_DOY, REPORT_DOW, REPORT_HOUR, OCC_YEAR, OCC_MONTH, OCC_DAY, OCC_DOY, OCC_DOW, OCC_HOUR, DIVISION, LOCATION_TYPE, PREMISES_TYPE, UCR_CODE, UCR_EXT, OFFENCE, MCI_CATEGORY, HOOD_158, NEIGHBOURHOOD_158, HOOD_140, NEIGHBOURHOOD_140, LONG_WGS84, LAT_WGS84]
Index: []

[0 rows x 31 columns]

In [4]:
print("\nNumber of duplicate rows:", crime_data.duplicated().sum())

Number of duplicate rows: 0

In [5]:
# Eliminate columns 'X' and 'Y'
crime_data = crime_data.drop(['X', 'Y'], axis=1)

# Set 'OBJECTID' as the new index
crime_data.set_index('OBJECTID', inplace=True)

In [6]:
crime_data

,EVENT_UNIQUE_ID,REPORT_DATE,OCC_DATE,REPORT_YEAR,REPORT_MONTH,REPORT_DAY,REPORT_DOY,REPORT_DOW,REPORT_HOUR,OCC_YEAR,...,UCR_CODE,UCR_EXT,OFFENCE,MCI_CATEGORY,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84
OBJECTID,,,,,,,,,,,,,,,,,,,,,
1,GO-20141260127,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,1,2014.0,...,1420,110,Assault Bodily Harm,Assault,84,Little Portugal,84,Little Portugal (84),-79.427105,43.642517
2,GO-20141263725,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,19,2014.0,...,1420,100,Assault With Weapon,Assault,78,Kensington-Chinatown,78,Kensington-Chinatown (78),-79.394234,43.654811
3,GO-20141264272,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,21,2014.0,...,1420,100,Assault With Weapon,Assault,85,South Parkdale,85,South Parkdale (85),-79.420532,43.638306
4,GO-20141263706,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,18,2014.0,...,1430,100,Assault,Assault,113,Weston,113,Weston (113),-79.505043,43.707365
5,GO-20141263710,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,18,2014.0,...,1430,100,Assault,Assault,151,Yonge-Doris,51,Willowdale East (51),-79.415293,43.778743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384683,GO-2024688981,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,Sunday,11,2024.0,...,2135,210,Theft Of Motor Vehicle,Auto Theft,136,West Hill,136,West Hill (136),-79.196001,43.755641
384684,GO-2024690900,2024/03/31 04:00:00+00,2024/03/31 04:00:00+00,2024,March,31,91,Sunday,16,2024.0,...,1430,100,Assault,Assault,19,Long Branch,19,Long Branch (19),-79.529766,43.595354
384685,GO-2024690985,2024/03/31 04:00:00+00,2024/03/31 04:00:00+00,2024,March,31,91,Sunday,16,2024.0,...,1430,100,Assault,Assault,98,Rosedale-Moore Park,98,Rosedale-Moore Park (98),-79.391479,43.688644
384686,GO-2024690995,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,Sunday,16,2024.0,...,2135,210,Theft Of Motor Vehicle,Auto Theft,98,Rosedale-Moore Park,98,Rosedale-Moore Park (98),-79.372581,43.684335
384687,GO-2024688279,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,Sunday,9,2024.0,...,2135,210,Theft Of Motor Vehicle,Auto Theft,133,Centennial Scarborough,133,Centennial Scarborough (133),-79.152912,43.781143

In [7]:
# Check for missing values in specific columns
missing_values = crime_data.isna().sum()

# Display the count of missing values in each column
print(missing_values)

EVENT_UNIQUE_ID        0
REPORT_DATE            0
OCC_DATE               0
REPORT_YEAR            0
REPORT_MONTH           0
REPORT_DAY             0
REPORT_DOY             0
REPORT_DOW             0
REPORT_HOUR            0
OCC_YEAR             121
OCC_MONTH            121
OCC_DAY              121
OCC_DOY              121
OCC_DOW              121
OCC_HOUR               0
DIVISION               0
LOCATION_TYPE          0
PREMISES_TYPE          0
UCR_CODE               0
UCR_EXT                0
OFFENCE                0
MCI_CATEGORY           0
HOOD_158               0
NEIGHBOURHOOD_158      0
HOOD_140               0
NEIGHBOURHOOD_140      0
LONG_WGS84             0
LAT_WGS84              0
dtype: int64

In [8]:
pd.set_option('display.max_columns', 40)
#pd.set_option('display.max_rows', None)

In [9]:
# Identify rows with missing values in specific columns
missing_rows = crime_data[crime_data[['OCC_YEAR', 'OCC_MONTH', 'OCC_DAY', 'OCC_DOY', 'OCC_DOW']].isna().any(axis=1)]

# Display the rows with missing values
missing_rows[['OCC_DATE', 'OCC_YEAR', 'OCC_MONTH', 'OCC_DAY', 'OCC_DOY', 'OCC_DOW']]

                        OCC_DATE  OCC_YEAR OCC_MONTH  OCC_DAY  OCC_DOY OCC_DOW
OBJECTID
77        1998/06/01 04:00:00+00       NaN       NaN      NaN      NaN     NaN
420       1996/01/31 05:00:00+00       NaN       NaN      NaN      NaN     NaN
1051      1980/01/01 05:00:00+00       NaN       NaN      NaN      NaN     NaN
1052      1980/01/01 05:00:00+00       NaN       NaN      NaN      NaN     NaN
3333      1999/10/01 04:00:00+00       NaN       NaN      NaN      NaN     NaN
...                          ...       ...       ...      ...      ...     ...
379685    1989/08/01 04:00:00+00       NaN       NaN      NaN      NaN     NaN
379980    1989/01/01 05:00:00+00       NaN       NaN      NaN      NaN     NaN
381193    1992/01/01 05:00:00+00       NaN       NaN      NaN      NaN     NaN
382402    1997/07/01 04:00:00+00       NaN       NaN      NaN      NaN     NaN
382435    1997/07/01 04:00:00+00       NaN       NaN      NaN      NaN     NaN

[121 rows x 6 columns]

In [10]:
crime_data[['OCC_YEAR']].value_counts()

OCC_YEAR
2023.0      48402
2022.0      41448
2019.0      40113
2018.0      37555
2017.0      35551
2020.0      35219
2021.0      34805
2016.0      33661
2015.0      32943
2014.0      32483
2024.0      10941
2013.0        627
2012.0        215
2011.0        143
2010.0        107
2009.0         83
2008.0         49
2007.0         38
2005.0         36
2004.0         32
2000.0         27
2006.0         24
2002.0         23
2001.0         22
2003.0         19
Name: count, dtype: int64

In [11]:
crime_data = crime_data[crime_data['OCC_YEAR'] >= 2014]

In [12]:
crime_data[['OCC_YEAR']].value_counts()

OCC_YEAR
2023.0      48402
2022.0      41448
2019.0      40113
2018.0      37555
2017.0      35551
2020.0      35219
2021.0      34805
2016.0      33661
2015.0      32943
2014.0      32483
2024.0      10941
Name: count, dtype: int64

In [13]:
# Identify rows with missing values in specific columns
missing_rows = crime_data[crime_data[['OCC_YEAR', 'OCC_MONTH', 'OCC_DAY', 'OCC_DOY', 'OCC_DOW']].isna().any(axis=1)]

# Display the rows with missing values
missing_rows[['OCC_DATE', 'OCC_YEAR', 'OCC_MONTH', 'OCC_DAY', 'OCC_DOY', 'OCC_DOW']]

Empty DataFrame
Columns: [OCC_DATE, OCC_YEAR, OCC_MONTH, OCC_DAY, OCC_DOY, OCC_DOW]
Index: []

In [14]:
crime_data['DIVISION'].value_counts()

#Not Specified Area (NSA) - 3899

DIVISION
D51    31616
D32    30264
D31    28147
D14    26710
D41    26601
D43    26576
D22    25553
D23    24916
D55    23599
D42    23119
D52    22694
D53    20403
D33    17158
D12    16555
D11    15294
D13    13770
D54     6292
NSA     3854
Name: count, dtype: int64

In [15]:
crime_data[crime_data['DIVISION'] == 'NSA']

,EVENT_UNIQUE_ID,REPORT_DATE,OCC_DATE,REPORT_YEAR,REPORT_MONTH,REPORT_DAY,REPORT_DOY,REPORT_DOW,REPORT_HOUR,OCC_YEAR,OCC_MONTH,OCC_DAY,OCC_DOY,OCC_DOW,OCC_HOUR,DIVISION,LOCATION_TYPE,PREMISES_TYPE,UCR_CODE,UCR_EXT,OFFENCE,MCI_CATEGORY,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84
OBJECTID,,,,,,,,,,,,,,,,,,,,,,,,,,,,
102,GO-20141260577,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,4,2014.0,January,1.0,1.0,Wednesday,2,NSA,"Streets, Roads, Highways (Bicycle Path, Privat...",Outside,1610,180,Robbery - Swarming,Robbery,NSA,NSA,NSA,NSA,0.0,0.0
103,GO-20141260973,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,4,2014.0,January,1.0,1.0,Wednesday,4,NSA,"Streets, Roads, Highways (Bicycle Path, Privat...",Outside,2130,210,Theft Over,Theft Over,NSA,NSA,NSA,NSA,0.0,0.0
104,GO-20141260537,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,4,2014.0,January,1.0,1.0,Wednesday,4,NSA,"Streets, Roads, Highways (Bicycle Path, Privat...",Outside,1430,100,Assault,Assault,NSA,NSA,NSA,NSA,0.0,0.0
105,GO-20141260577,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,4,2014.0,January,1.0,1.0,Wednesday,2,NSA,"Streets, Roads, Highways (Bicycle Path, Privat...",Outside,1610,200,Robbery - Mugging,Robbery,NSA,NSA,NSA,NSA,0.0,0.0
133,GO-20141270511,2014/01/02 05:00:00+00,2014/01/02 05:00:00+00,2014,January,2,2,Thursday,23,2014.0,January,2.0,2.0,Thursday,21,NSA,"Streets, Roads, Highways (Bicycle Path, Privat...",Outside,1610,220,Robbery - Other,Robbery,NSA,NSA,NSA,NSA,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383938,GO-2024649543,2024/03/26 04:00:00+00,2024/03/26 04:00:00+00,2024,March,26,86,Tuesday,8,2024.0,March,26.0,86.0,Tuesday,1,NSA,"Apartment (Rooming House, Condo)",Apartment,1430,100,Assault,Assault,NSA,NSA,NSA,NSA,0.0,0.0
383939,GO-2024649543,2024/03/26 04:00:00+00,2024/03/26 04:00:00+00,2024,March,26,86,Tuesday,8,2024.0,March,26.0,86.0,Tuesday,1,NSA,"Apartment (Rooming House, Condo)",Apartment,2120,200,B&E,Break and Enter,NSA,NSA,NSA,NSA,0.0,0.0
383941,GO-2024655271,2024/03/26 04:00:00+00,2022/10/12 04:00:00+00,2024,March,26,86,Tuesday,22,2022.0,October,12.0,285.0,Wednesday,0,NSA,"Single Home, House (Attach Garage, Cottage, Mo...",House,1430,100,Assault,Assault,NSA,NSA,NSA,NSA,0.0,0.0
384363,GO-2024672828,2024/03/29 04:00:00+00,2023/11/18 05:00:00+00,2024,March,29,89,Friday,2,2023.0,November,18.0,322.0,Saturday,0,NSA,"Commercial Dwelling Unit (Hotel, Motel, B & B,...",Commercial,1430,100,Assault,Assault,NSA,NSA,NSA,NSA,0.0,0.0
384579,GO-2024682430,2024/03/30 04:00:00+00,2024/03/30 04:00:00+00,2024,March,30,90,Saturday,22,2024.0,March,30.0,90.0,Saturday,22,NSA,"Apartment (Rooming House, Condo)",Apartment,1430,100,Assault,Assault,NSA,NSA,NSA,NSA,0.0,0.0

In [16]:
crime_data[['HOOD_158','NEIGHBOURHOOD_158', 'HOOD_140', 'NEIGHBOURHOOD_140', 'LONG_WGS84','LAT_WGS84']].value_counts()

HOOD_158  NEIGHBOURHOOD_158      HOOD_140  NEIGHBOURHOOD_140                         LONG_WGS84  LAT_WGS84
NSA       NSA                    NSA       NSA                                        0.000000   0.000000     5783
160       Mimico-Queensway       17        Mimico (includes Humber Bay Shores) (17)  -79.515814  43.612080    1830
168       Downtown Yonge East    75        Church-Yonge Corridor (75)                -79.380913  43.656325    1156
73        Moss Park              73        Moss Park (73)                            -79.371003  43.658297    1087
156       Bendale-Glen Andrew    127       Bendale (127)                             -79.254241  43.776636     960
                                                                                                              ...
37        Willowdale West        36        Newtonbrook West (36)                     -79.420294  43.778715       1
122       Birchcliffe-Cliffside  122       Birchcliffe-Cliffside (122)               -79.267531  43.687571       1
                                                                                     -79.267442  43.694088       1
160       Mimico-Queensway       17        Mimico (includes Humber Bay Shores) (17)  -79.490262  43.615936       1
158       Islington              14        Islington-City Centre West (14)           -79.555899  43.645082       1
Name: count, Length: 21835, dtype: int64

In [17]:
#crime_data = crime_data[(crime_data['LONG_WGS84'] < -78.0000)]
#crime_data

In [18]:
crime_data[crime_data['DIVISION'] == 'NSA']

,EVENT_UNIQUE_ID,REPORT_DATE,OCC_DATE,REPORT_YEAR,REPORT_MONTH,REPORT_DAY,REPORT_DOY,REPORT_DOW,REPORT_HOUR,OCC_YEAR,OCC_MONTH,OCC_DAY,OCC_DOY,OCC_DOW,OCC_HOUR,DIVISION,LOCATION_TYPE,PREMISES_TYPE,UCR_CODE,UCR_EXT,OFFENCE,MCI_CATEGORY,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84
OBJECTID,,,,,,,,,,,,,,,,,,,,,,,,,,,,
102,GO-20141260577,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,4,2014.0,January,1.0,1.0,Wednesday,2,NSA,"Streets, Roads, Highways (Bicycle Path, Privat...",Outside,1610,180,Robbery - Swarming,Robbery,NSA,NSA,NSA,NSA,0.0,0.0
103,GO-20141260973,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,4,2014.0,January,1.0,1.0,Wednesday,4,NSA,"Streets, Roads, Highways (Bicycle Path, Privat...",Outside,2130,210,Theft Over,Theft Over,NSA,NSA,NSA,NSA,0.0,0.0
104,GO-20141260537,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,4,2014.0,January,1.0,1.0,Wednesday,4,NSA,"Streets, Roads, Highways (Bicycle Path, Privat...",Outside,1430,100,Assault,Assault,NSA,NSA,NSA,NSA,0.0,0.0
105,GO-20141260577,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,4,2014.0,January,1.0,1.0,Wednesday,2,NSA,"Streets, Roads, Highways (Bicycle Path, Privat...",Outside,1610,200,Robbery - Mugging,Robbery,NSA,NSA,NSA,NSA,0.0,0.0
133,GO-20141270511,2014/01/02 05:00:00+00,2014/01/02 05:00:00+00,2014,January,2,2,Thursday,23,2014.0,January,2.0,2.0,Thursday,21,NSA,"Streets, Roads, Highways (Bicycle Path, Privat...",Outside,1610,220,Robbery - Other,Robbery,NSA,NSA,NSA,NSA,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383938,GO-2024649543,2024/03/26 04:00:00+00,2024/03/26 04:00:00+00,2024,March,26,86,Tuesday,8,2024.0,March,26.0,86.0,Tuesday,1,NSA,"Apartment (Rooming House, Condo)",Apartment,1430,100,Assault,Assault,NSA,NSA,NSA,NSA,0.0,0.0
383939,GO-2024649543,2024/03/26 04:00:00+00,2024/03/26 04:00:00+00,2024,March,26,86,Tuesday,8,2024.0,March,26.0,86.0,Tuesday,1,NSA,"Apartment (Rooming House, Condo)",Apartment,2120,200,B&E,Break and Enter,NSA,NSA,NSA,NSA,0.0,0.0
383941,GO-2024655271,2024/03/26 04:00:00+00,2022/10/12 04:00:00+00,2024,March,26,86,Tuesday,22,2022.0,October,12.0,285.0,Wednesday,0,NSA,"Single Home, House (Attach Garage, Cottage, Mo...",House,1430,100,Assault,Assault,NSA,NSA,NSA,NSA,0.0,0.0
384363,GO-2024672828,2024/03/29 04:00:00+00,2023/11/18 05:00:00+00,2024,March,29,89,Friday,2,2023.0,November,18.0,322.0,Saturday,0,NSA,"Commercial Dwelling Unit (Hotel, Motel, B & B,...",Commercial,1430,100,Assault,Assault,NSA,NSA,NSA,NSA,0.0,0.0
384579,GO-2024682430,2024/03/30 04:00:00+00,2024/03/30 04:00:00+00,2024,March,30,90,Saturday,22,2024.0,March,30.0,90.0,Saturday,22,NSA,"Apartment (Rooming House, Condo)",Apartment,1430,100,Assault,Assault,NSA,NSA,NSA,NSA,0.0,0.0

In [19]:
crime_data = crime_data[crime_data['DIVISION'] != 'NSA']
crime_data

,EVENT_UNIQUE_ID,REPORT_DATE,OCC_DATE,REPORT_YEAR,REPORT_MONTH,REPORT_DAY,REPORT_DOY,REPORT_DOW,REPORT_HOUR,OCC_YEAR,OCC_MONTH,OCC_DAY,OCC_DOY,OCC_DOW,OCC_HOUR,DIVISION,LOCATION_TYPE,PREMISES_TYPE,UCR_CODE,UCR_EXT,OFFENCE,MCI_CATEGORY,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84
OBJECTID,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,GO-20141260127,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,1,2014.0,January,1.0,1.0,Wednesday,1,D14,Bar / Restaurant,Commercial,1420,110,Assault Bodily Harm,Assault,84,Little Portugal,84,Little Portugal (84),-79.427105,43.642517
2,GO-20141263725,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,19,2014.0,January,1.0,1.0,Wednesday,18,D52,"Apartment (Rooming House, Condo)",Apartment,1420,100,Assault With Weapon,Assault,78,Kensington-Chinatown,78,Kensington-Chinatown (78),-79.394234,43.654811
3,GO-20141264272,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,21,2014.0,January,1.0,1.0,Wednesday,21,D14,"Apartment (Rooming House, Condo)",Apartment,1420,100,Assault With Weapon,Assault,85,South Parkdale,85,South Parkdale (85),-79.420532,43.638306
4,GO-20141263706,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,18,2014.0,January,1.0,1.0,Wednesday,18,D12,"Single Home, House (Attach Garage, Cottage, Mo...",House,1430,100,Assault,Assault,113,Weston,113,Weston (113),-79.505043,43.707365
5,GO-20141263710,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,18,2014.0,January,1.0,1.0,Wednesday,18,D32,"Apartment (Rooming House, Condo)",Apartment,1430,100,Assault,Assault,151,Yonge-Doris,51,Willowdale East (51),-79.415293,43.778743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384683,GO-2024688981,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,Sunday,11,2024.0,March,30.0,90.0,Saturday,16,D43,"Parking Lots (Apt., Commercial Or Non-Commercial)",Outside,2135,210,Theft Of Motor Vehicle,Auto Theft,136,West Hill,136,West Hill (136),-79.196001,43.755641
384684,GO-2024690900,2024/03/31 04:00:00+00,2024/03/31 04:00:00+00,2024,March,31,91,Sunday,16,2024.0,March,31.0,91.0,Sunday,16,D22,"Apartment (Rooming House, Condo)",Apartment,1430,100,Assault,Assault,19,Long Branch,19,Long Branch (19),-79.529766,43.595354
384685,GO-2024690985,2024/03/31 04:00:00+00,2024/03/31 04:00:00+00,2024,March,31,91,Sunday,16,2024.0,March,31.0,91.0,Sunday,16,D53,Schools During Un-Supervised Activity,Educational,1430,100,Assault,Assault,98,Rosedale-Moore Park,98,Rosedale-Moore Park (98),-79.391479,43.688644
384686,GO-2024690995,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,Sunday,16,2024.0,March,30.0,90.0,Saturday,23,D53,"Single Home, House (Attach Garage, Cottage, Mo...",House,2135,210,Theft Of Motor Vehicle,Auto Theft,98,Rosedale-Moore Park,98,Rosedale-Moore Park (98),-79.372581,43.684335
384687,GO-2024688279,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,Sunday,9,2024.0,March,30.0,90.0,Saturday,19,D43,"Single Home, House (Attach Garage, Cottage, Mo...",House,2135,210,Theft Of Motor Vehicle,Auto Theft,133,Centennial Scarborough,133,Centennial Scarborough (133),-79.152912,43.781143

In [20]:
crime_data['DIVISION'].value_counts()

DIVISION
D51    31616
D32    30264
D31    28147
D14    26710
D41    26601
D43    26576
D22    25553
D23    24916
D55    23599
D42    23119
D52    22694
D53    20403
D33    17158
D12    16555
D11    15294
D13    13770
D54     6292
Name: count, dtype: int64

In [21]:
crime_data['DIVISION'].value_counts()

DIVISION
D51    31616
D32    30264
D31    28147
D14    26710
D41    26601
D43    26576
D22    25553
D23    24916
D55    23599
D42    23119
D52    22694
D53    20403
D33    17158
D12    16555
D11    15294
D13    13770
D54     6292
Name: count, dtype: int64

In [22]:
crime_data['LOCATION_TYPE'].value_counts()
# Unknown - 995
# Unknown - 901

LOCATION_TYPE
Apartment (Rooming House, Condo)                                          89297
Single Home, House (Attach Garage, Cottage, Mobile)                       68943
Streets, Roads, Highways (Bicycle Path, Private Road)                     58509
Other Commercial / Corporate Places (For Profit, Warehouse, Corp. Bldg    43757
Parking Lots (Apt., Commercial Or Non-Commercial)                         34745
Bar / Restaurant                                                          14536
Open Areas (Lakes, Parks, Rivers)                                          7442
Schools During Supervised Activity                                         5662
Ttc Subway Station                                                         4929
Convenience Stores                                                         4860
Commercial Dwelling Unit (Hotel, Motel, B & B, Short Term Rental)          4132
Private Property Structure (Pool, Shed, Detached Garage)                   3900
Hospital / Institutions / Medical Facilities (Clinic, Dentist, Morgue)     3273
Ttc Bus                                                                    3265
Schools During Un-Supervised Activity                                      3188
Other Non Commercial / Corporate Places (Non-Profit, Gov'T, Firehall)      3098
Jails / Detention Centres                                                  2567
Homeless Shelter / Mission                                                 2481
Construction Site (Warehouse, Trailer, Shed)                               2426
Bank And Other Financial Institutions (Money Mart, Tsx)                    2009
Gas Station (Self, Full, Attached Convenience)                             1969
Dealership (Car, Motorcycle, Marine, Trailer, Etc.)                        1898
Group Homes (Non-Profit, Halfway House, Social Agency)                     1442
Ttc Subway Train                                                           1212
Pharmacy                                                                   1136
Ttc Bus Stop / Shelter / Loop                                              1037
Police / Courts (Parole Board, Probation Office)                            941
Nursing Home                                                                932
Religious Facilities (Synagogue, Church, Convent, Mosque)                   911
Unknown                                                                     901
Ttc Street Car                                                              701
Universities / Colleges                                                     690
Retirement Home                                                             616
Go Station                                                                  540
Community Group Home                                                        321
Other Passenger Train Station                                               142
Other Regional Transit System Vehicle                                       124
Ttc Light Rail Transit Station                                              121
Group Homes (Non-Profit, Halfway House,                                     109
Go Train                                                                     88
Go Bus                                                                       76
Ttc Admin Or Support Facility                                                60
Other Passenger Train                                                        41
Ttc Bus Garage                                                               34
Halfway House                                                                32
Ttc Light Rail Vehicle                                                       31
Ttc Subway Tunnel / Outdoor Tracks                                           25
Other Train Admin Or Support Facility                                        25
Other Train Tracks                                                           24
Other Train Yard                                                             20
Ttc Wheel Trans Vehicle                                                      17
Halfway House / Young Offender Group Home                                    17
Cargo Train                                                                  13
Ttc Support Vehicle                                                           2
Name: count, dtype: int64

In [23]:
crime_data['PREMISES_TYPE'].value_counts()
#Other           23012

PREMISES_TYPE
Outside        101753
Apartment       89297
Commercial      75587
House           68943
Other           22714
Transit         11433
Educational      9540
Name: count, dtype: int64

In [24]:
crime_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 379267 entries, 1 to 384687
Data columns (total 28 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   EVENT_UNIQUE_ID    379267 non-null  object
 1   REPORT_DATE        379267 non-null  object
 2   OCC_DATE           379267 non-null  object
 3   REPORT_YEAR        379267 non-null  int64
 4   REPORT_MONTH       379267 non-null  object
 5   REPORT_DAY         379267 non-null  int64
 6   REPORT_DOY         379267 non-null  int64
 7   REPORT_DOW         379267 non-null  object
 8   REPORT_HOUR        379267 non-null  int64
 9   OCC_YEAR           379267 non-null  float64
 10  OCC_MONTH          379267 non-null  object
 11  OCC_DAY            379267 non-null  float64
 12  OCC_DOY            379267 non-null  float64
 13  OCC_DOW            379267 non-null  object
 14  OCC_HOUR           379267 non-null  int64
 15  DIVISION           379267 non-null  object
 16  LOCATION_TYPE      379267 non-null  object
 17  PREMISES_TYPE      379267 non-null  object
 18  UCR_CODE           379267 non-null  int64
 19  UCR_EXT            379267 non-null  int64
 20  OFFENCE            379267 non-null  object
 21  MCI_CATEGORY       379267 non-null  object
 22  HOOD_158           379267 non-null  object
 23  NEIGHBOURHOOD_158  379267 non-null  object
 24  HOOD_140           379267 non-null  object
 25  NEIGHBOURHOOD_140  379267 non-null  object
 26  LONG_WGS84         379267 non-null  float64
 27  LAT_WGS84          379267 non-null  float64
dtypes: float64(5), int64(7), object(16)
memory usage: 83.9+ MB

In [25]:
crime_data

,EVENT_UNIQUE_ID,REPORT_DATE,OCC_DATE,REPORT_YEAR,REPORT_MONTH,REPORT_DAY,REPORT_DOY,REPORT_DOW,REPORT_HOUR,OCC_YEAR,OCC_MONTH,OCC_DAY,OCC_DOY,OCC_DOW,OCC_HOUR,DIVISION,LOCATION_TYPE,PREMISES_TYPE,UCR_CODE,UCR_EXT,OFFENCE,MCI_CATEGORY,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84
OBJECTID,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,GO-20141260127,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,1,2014.0,January,1.0,1.0,Wednesday,1,D14,Bar / Restaurant,Commercial,1420,110,Assault Bodily Harm,Assault,84,Little Portugal,84,Little Portugal (84),-79.427105,43.642517
2,GO-20141263725,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,19,2014.0,January,1.0,1.0,Wednesday,18,D52,"Apartment (Rooming House, Condo)",Apartment,1420,100,Assault With Weapon,Assault,78,Kensington-Chinatown,78,Kensington-Chinatown (78),-79.394234,43.654811
3,GO-20141264272,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,21,2014.0,January,1.0,1.0,Wednesday,21,D14,"Apartment (Rooming House, Condo)",Apartment,1420,100,Assault With Weapon,Assault,85,South Parkdale,85,South Parkdale (85),-79.420532,43.638306
4,GO-20141263706,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,18,2014.0,January,1.0,1.0,Wednesday,18,D12,"Single Home, House (Attach Garage, Cottage, Mo...",House,1430,100,Assault,Assault,113,Weston,113,Weston (113),-79.505043,43.707365
5,GO-20141263710,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,18,2014.0,January,1.0,1.0,Wednesday,18,D32,"Apartment (Rooming House, Condo)",Apartment,1430,100,Assault,Assault,151,Yonge-Doris,51,Willowdale East (51),-79.415293,43.778743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384683,GO-2024688981,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,Sunday,11,2024.0,March,30.0,90.0,Saturday,16,D43,"Parking Lots (Apt., Commercial Or Non-Commercial)",Outside,2135,210,Theft Of Motor Vehicle,Auto Theft,136,West Hill,136,West Hill (136),-79.196001,43.755641
384684,GO-2024690900,2024/03/31 04:00:00+00,2024/03/31 04:00:00+00,2024,March,31,91,Sunday,16,2024.0,March,31.0,91.0,Sunday,16,D22,"Apartment (Rooming House, Condo)",Apartment,1430,100,Assault,Assault,19,Long Branch,19,Long Branch (19),-79.529766,43.595354
384685,GO-2024690985,2024/03/31 04:00:00+00,2024/03/31 04:00:00+00,2024,March,31,91,Sunday,16,2024.0,March,31.0,91.0,Sunday,16,D53,Schools During Un-Supervised Activity,Educational,1430,100,Assault,Assault,98,Rosedale-Moore Park,98,Rosedale-Moore Park (98),-79.391479,43.688644
384686,GO-2024690995,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,Sunday,16,2024.0,March,30.0,90.0,Saturday,23,D53,"Single Home, House (Attach Garage, Cottage, Mo...",House,2135,210,Theft Of Motor Vehicle,Auto Theft,98,Rosedale-Moore Park,98,Rosedale-Moore Park (98),-79.372581,43.684335
384687,GO-2024688279,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,Sunday,9,2024.0,March,30.0,90.0,Saturday,19,D43,"Single Home, House (Attach Garage, Cottage, Mo...",House,2135,210,Theft Of Motor Vehicle,Auto Theft,133,Centennial Scarborough,133,Centennial Scarborough (133),-79.152912,43.781143

In [26]:
# checking for latitude and longitude errors

# Toronto boundaries
north_boundary = 43.8554
south_boundary = 43.5810
east_boundary = -79.1161
west_boundary = -79.6393

# Check if latitude and longitude are within the boundaries
within_boundaries = (crime_data['LAT_WGS84'] <= north_boundary) & (crime_data['LAT_WGS84'] >= south_boundary) & \
                    (crime_data['LONG_WGS84'] >= west_boundary) & (crime_data['LONG_WGS84'] <= east_boundary)

# Filter the DataFrame
data_within_toronto = crime_data[within_boundaries]

data_within_toronto

,EVENT_UNIQUE_ID,REPORT_DATE,OCC_DATE,REPORT_YEAR,REPORT_MONTH,REPORT_DAY,REPORT_DOY,REPORT_DOW,REPORT_HOUR,OCC_YEAR,OCC_MONTH,OCC_DAY,OCC_DOY,OCC_DOW,OCC_HOUR,DIVISION,LOCATION_TYPE,PREMISES_TYPE,UCR_CODE,UCR_EXT,OFFENCE,MCI_CATEGORY,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84
OBJECTID,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,GO-20141260127,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,1,2014.0,January,1.0,1.0,Wednesday,1,D14,Bar / Restaurant,Commercial,1420,110,Assault Bodily Harm,Assault,84,Little Portugal,84,Little Portugal (84),-79.427105,43.642517
2,GO-20141263725,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,19,2014.0,January,1.0,1.0,Wednesday,18,D52,"Apartment (Rooming House, Condo)",Apartment,1420,100,Assault With Weapon,Assault,78,Kensington-Chinatown,78,Kensington-Chinatown (78),-79.394234,43.654811
3,GO-20141264272,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,21,2014.0,January,1.0,1.0,Wednesday,21,D14,"Apartment (Rooming House, Condo)",Apartment,1420,100,Assault With Weapon,Assault,85,South Parkdale,85,South Parkdale (85),-79.420532,43.638306
4,GO-20141263706,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,18,2014.0,January,1.0,1.0,Wednesday,18,D12,"Single Home, House (Attach Garage, Cottage, Mo...",House,1430,100,Assault,Assault,113,Weston,113,Weston (113),-79.505043,43.707365
5,GO-20141263710,2014/01/01 05:00:00+00,2014/01/01 05:00:00+00,2014,January,1,1,Wednesday,18,2014.0,January,1.0,1.0,Wednesday,18,D32,"Apartment (Rooming House, Condo)",Apartment,1430,100,Assault,Assault,151,Yonge-Doris,51,Willowdale East (51),-79.415293,43.778743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384683,GO-2024688981,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,Sunday,11,2024.0,March,30.0,90.0,Saturday,16,D43,"Parking Lots (Apt., Commercial Or Non-Commercial)",Outside,2135,210,Theft Of Motor Vehicle,Auto Theft,136,West Hill,136,West Hill (136),-79.196001,43.755641
384684,GO-2024690900,2024/03/31 04:00:00+00,2024/03/31 04:00:00+00,2024,March,31,91,Sunday,16,2024.0,March,31.0,91.0,Sunday,16,D22,"Apartment (Rooming House, Condo)",Apartment,1430,100,Assault,Assault,19,Long Branch,19,Long Branch (19),-79.529766,43.595354
384685,GO-2024690985,2024/03/31 04:00:00+00,2024/03/31 04:00:00+00,2024,March,31,91,Sunday,16,2024.0,March,31.0,91.0,Sunday,16,D53,Schools During Un-Supervised Activity,Educational,1430,100,Assault,Assault,98,Rosedale-Moore Park,98,Rosedale-Moore Park (98),-79.391479,43.688644
384686,GO-2024690995,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,Sunday,16,2024.0,March,30.0,90.0,Saturday,23,D53,"Single Home, House (Attach Garage, Cottage, Mo...",House,2135,210,Theft Of Motor Vehicle,Auto Theft,98,Rosedale-Moore Park,98,Rosedale-Moore Park (98),-79.372581,43.684335
384687,GO-2024688279,2024/03/31 04:00:00+00,2024/03/30 04:00:00+00,2024,March,31,91,Sunday,9,2024.0,March,30.0,90.0,Saturday,19,D43,"Single Home, House (Attach Garage, Cottage, Mo...",House,2135,210,Theft Of Motor Vehicle,Auto Theft,133,Centennial Scarborough,133,Centennial Scarborough (133),-79.152912,43.781143

In [27]:
# Apply multiple conditions to filter rows based on longitude and latitude
# filtered_crime_data = crime_data[
#     (crime_data['LONG_WGS84'] < -79.639247) |
#     (crime_data['LONG_WGS84'] > -79.321396) |
#     (crime_data['LAT_WGS84'] < 43.659776) |
#     (crime_data['LAT_WGS84'] > 43.853164)
# ]
crime_data = crime_data[
     (crime_data['LONG_WGS84'] < -78.0000)]

# Display the filtered DataFrame
crime_data['LONG_WGS84'].value_counts()

LONG_WGS84
-79.515814    1830
-79.380913    1283
-79.371003    1087
-79.254241     960
-79.451306     898
              ...
-79.520685       1
-79.278863       1
-79.509926       1
-79.408936       1
-79.152912       1
Name: count, Length: 19096, dtype: int64

In [32]:
if data_within_toronto.shape == crime_data.shape:
    print("perfeito")
else:
    print("errado")

perfeito

In [ ]:
crime_data['OCC_DATE'] = pd.to_datetime(crime_data['OCC_DATE'], errors='coerce')
crime_data['REPORT_DATE'] = pd.to_datetime(crime_data['REPORT_DATE'], errors='coerce')
crime_data.info()

In [ ]:
crime_data[['OCC_DATE', 'REPORT_DATE']].value_counts()

In [ ]:
# Histogram para visualizar a distribuição dos dados
plt.figure(figsize=(20, 20))  # Increase size for better visibility
crime_data.hist(bins=50, figsize=(20, 20))
plt.suptitle('Histograms of Numerical Columns', fontsize=24)
plt.show()

In [ ]:
# Eliminate columns 'X' and 'Y'
crime_data = crime_data.drop(['X', 'Y'], axis=1)

# Set 'OBJECTID' as the new index
crime_data.set_index('OBJECTID', inplace=True)

# Padronização de categorização
crime_data['DIVISION'] = crime_data['DIVISION'].str.lower().str.strip()
crime_data['LOCATION_TYPE'] = crime_data['LOCATION_TYPE'].str.lower()#.str.strip()
#crime_data['PREMISES_TYPE'] = crime_data['PREMISES_TYPE'].str.lower().str.strip()

# Drop rows where OCC was before 2014
crime_data = crime_data[crime_data['OCC_YEAR'] >= 2014]

# Drop rows where the value in the 'DIVISION' column is 'NSA'
crime_data = crime_data[crime_data['DIVISION'] != 'NSA']

# Convert OCC_DATE and REPORT_DATE to datetime
crime_data['OCC_DATE'] = pd.to_datetime(crime_data['OCC_DATE'], errors='coerce')
crime_data['REPORT_DATE'] = pd.to_datetime(crime_data['REPORT_DATE'], errors='coerce')

# Data validation
crime_data = crime_data[crime_data['OCC_DATE'] <= crime_data['REPORT_DATE']]
crime_data = crime_data[(crime_data['REPORT_HOUR'] >= 0) & (crime_data['REPORT_HOUR'] <= 23)]
crime_data = crime_data[(crime_data['OCC_HOUR'] >= 0) & (crime_data['OCC_HOUR'] <= 23)]

# Creating new features
crime_data['REPORT_DAY_OF_WEEK'] = crime_data['REPORT_DATE'].dt.dayofweek
crime_data['OCC_DAY_OF_WEEK'] = crime_data['OCC_DATE'].dt.dayofweek

# Outliers
crime_data = crime_data[(crime_data['LONG_WGS84'] < -78.0000)]
#crime_data = crime_data[(crime_data['LONG_WGS84'] >= -79.639247) & (crime_data['LONG_WGS84'] <= -79.321396)]
#crime_data = crime_data[(crime_data['LAT_WGS84'] >= 43.659776) & (crime_data['LAT_WGS84'] <= 43.853164)]

# Conversão de categorias em números (One-Hot Encoding)
crime_data = pd.get_dummies(crime_data, columns=['DIVISION', 'LOCATION_TYPE', 'PREMISES_TYPE', 'OFFENCE', 'MCI_CATEGORY', 'NEIGHBOURHOOD_158', 'NEIGHBOURHOOD_140'])

# Exibir as primeiras linhas do dataset limpo
crime_data.head()